name: Update News
on:
  schedule:
    - cron: '0 * * * *' # 每小时运行
  workflow_dispatch: # 手动运行

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://lekeopen.com/rss.xml"
          max_post_count: 5
          # 加上日期格式配置
          date_format: "yyyy-mm-dd"
          # 修改模板，把日期放在前面
          template: "$newline- [$date] [$title]($url)"
          readme_path: "profile/README.md"
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
